import Head from "next/head";
import { Inter } from "next/font/google";
import BannerSlider from "../components/home/BannerSlider";
import Testimonial from "@/components/home/Testimonial";
import Brand from "@/components/home/Brand";
import FlashDeal from "@/components/home/FlashDeal";
import Category from "@/components/home/Category";
import LowMOQ from "@/components/home/LowMOQ";
import AdsBanner from "@/components/home/AdsBanner";
import Under100 from "@/components/home/Under100";
import TopCategoryProducts from "@/components/home/TopCategoryProducts";
import SingleProduct from "@/components/home/SingleProduct";
import SeasonalProduct from "@/components/home/SeasonalProduct";
import Blogs from "@/components/home/Blogs";
import Input from "@/components/inputs/Input";
import BtnFull from "@/components/buttons/BtnFull";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <div className={`${inter.className} bg-gray-300`}>
            <Head>
                <title>Beekolpo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BannerSlider />
            <FlashDeal />
            <Category />
            <LowMOQ />
            <AdsBanner />
            <Under100 />
            <TopCategoryProducts />
            <SingleProduct />
            <SeasonalProduct />
            <Testimonial />
            <Brand />
            <Blogs />
        </div>
    );
}
